create table if not exists public.partner_inquiries (
  id bigint generated by default as identity primary key,
  contact_name text not null,
  email text not null,
  phone text,
  message text,
  created_at timestamptz not null default now()
);

alter table public.partner_inquiries enable row level security;

drop policy if exists "Anyone can submit partner inquiries" on public.partner_inquiries;

create policy "Anyone can submit partner inquiries"
on public.partner_inquiries
for insert
to anon, authenticated
with check (true);
