create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamptz not null default now()
);

alter table public.subscriptions enable row level security;

drop policy if exists "Anyone can subscribe" on public.subscriptions;

create policy "Anyone can subscribe"
on public.subscriptions
for insert
to anon, authenticated
with check (true);
